// Universe stock names and sector metadata
// Extracted from routes.ts — shared across stocks and search routes

export const UNIVERSE_STOCK_NAMES: Record<string, string> = {
  BBCA: "Bank Central Asia Tbk",
  ADRO: "Adaro Energy Indonesia Tbk",
  UNTR: "United Tractors Tbk",
  ICBP: "Indofood CBP Sukses Makmur Tbk",
  UNVR: "Unilever Indonesia Tbk",
  BBRI: "Bank Rakyat Indonesia (Persero) Tbk",
  BMRI: "Bank Mandiri (Persero) Tbk",
  BBNI: "Bank Negara Indonesia (Persero) Tbk",
  BRIS: "Bank Syariah Indonesia Tbk",
  ARTO: "Bank Jago Tbk",
  TLKM: "Telkom Indonesia (Persero) Tbk",
  ISAT: "Indosat Tbk",
  EXCL: "XL Axiata Tbk",
  TOWR: "Sarana Menara Nusantara Tbk",
  INDF: "Indofood Sukses Makmur Tbk",
  MYOR: "Mayora Indah Tbk",
  KLBF: "Kalbe Farma Tbk",
  SIDO: "Industri Jamu dan Farmasi Sido Muncul Tbk",
  AMRT: "Sumber Alfaria Trijaya Tbk",
  ASII: "Astra International Tbk",
  ACES: "Ace Hardware Indonesia Tbk",
  MAPI: "Mitra Adiperkasa Tbk",
  ERAA: "Erajaya Swasembada Tbk",
  PTBA: "Bukit Asam Tbk",
  ITMG: "Indo Tambangraya Megah Tbk",
  MEDC: "Medco Energi Internasional Tbk",
  HRUM: "Harum Energy Tbk",
  AKRA: "AKR Corporindo Tbk",
  INCO: "Vale Indonesia Tbk",
  ANTM: "Aneka Tambang Tbk",
  MDKA: "Merdeka Copper Gold Tbk",
  TINS: "Timah Tbk",
  INKP: "Indah Kiat Pulp & Paper Tbk",
  TPIA: "Chandra Asri Pacific Tbk",
  JSMR: "Jasa Marga (Persero) Tbk",
  WIKA: "Wijaya Karya (Persero) Tbk",
  BSDE: "Bumi Serpong Damai Tbk",
  CTRA: "Ciputra Development Tbk",
  PWON: "Pakuwon Jati Tbk",
  SMRA: "Summarecon Agung Tbk",
  GOTO: "GoTo Gojek Tokopedia Tbk",
  BUKA: "Bukalapak.com Tbk",
  EMTK: "Elang Mahkota Teknologi Tbk",
  BREN: "Barito Renewables Energy Tbk",
  AALI: "Astra Agro Lestari Tbk",
  LSIP: "PP London Sumatra Indonesia Tbk",
};

export const UNIVERSE_STOCK_SECTORS: Record<string, { sector: string; subsector: string; sectorBadge: string }> = {
  ADRO: { sector: "Energy",      subsector: "Coal Mining",   sectorBadge: "SEKTOR ENERGI" },
  UNTR: { sector: "Industrials", subsector: "Heavy Equipment", sectorBadge: "SEKTOR INDUSTRI" },
  ICBP: { sector: "Consumer Staples", subsector: "Food & Beverages", sectorBadge: "SEKTOR KONSUMER" },
};
